version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak_gestor_fe
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"
    volumes:
      - ./gestor-fe-realm.json:/opt/keycloak/data/import/gestor-fe-realm.json
    command:
      - start-dev
      - --import-realm