spring.application.name=gestor-fe-core-service
server.port=9096

spring.datasource.url= jdbc:postgresql://localhost:5434/gestor_fe_core_db
spring.datasource.username=postgres
spring.datasource.password=ESS10W@A
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update

# Los JOBs de Spring Batch no se ejecutan al arrancar Sprint
spring.batch.job.enabled=false
spring.main.allow-bean-definition-overriding=true
# Inicializar el schema para Spring Batch. Esto es, crea las tablas que se requieren
spring.batch.initialize-schema=never


setCorePoolSize=10
setMaxPoolSize=20
ruta.storage = E:\\gestion-fe\\