spring.application.name=gestor-fe-core-service
server.port=9096

spring.datasource.url= jdbc:postgresql://localhost:5434/gestor_fe_core_db
spring.datasource.username=postgres
spring.datasource.password=ESS10W@A
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update

# Los JOBs de Spring Batch no se ejecutan al arrancar Sprint
spring.batch.job.enabled=false
spring.main.allow-bean-definition-overriding=true
# Inicializar el schema para Spring Batch. Esto es, crea las tablas que se requieren
spring.batch.jdbc.initialize-schema=always



setCorePoolSize=10
setMaxPoolSize=20
ruta.storage=E:\\gestion-fe\\
ruta.storage.validos=E:\\gestion-fe-validos\\
#ruta.storage=C:\\Users\\USUARIO01\\Documents\\WilmerA\\soportes-documentales-fe\\
#ruta.storage.validos=C:\\Users\\USUARIO01\\Documents\\WilmerA\\soportes-documentales-fe-validos\\

# Silenciar el StackTrace ruidoso de Spring Batch al fallar validaciones de negocio
logging.level.org.springframework.batch.core.step.AbstractStep=OFF
logging.level.org.springframework.batch.core.step.item.FaultTolerantChunkProcessor=OFF

admin-service.url:http://localhost:9095

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false